[package]
name = "rgvg"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = { version = "0.10", default-features = false }
log = "0.4.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.6"
